# Generated by Django 4.0.4 on 2022-05-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_employee_delete_datas_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eemail',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eid',
        ),
    ]
